In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weatherHistory.csv")

In [3]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [4]:
df.tail()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [5]:
df.shape

(96453, 12)

In [6]:
df.size

1157436

In [7]:
df.index

RangeIndex(start=0, stop=96453, step=1)

In [8]:
df.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [10]:
df.dtypes

Formatted Date               object
Summary                      object
Precip Type                  object
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)      float64
Visibility (km)             float64
Loud Cover                  float64
Pressure (millibars)        float64
Daily Summary                object
dtype: object

In [11]:
df.describe()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
count,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.0,96453.000000
mean,11.932678,10.855029,0.734899,10.810640,187.509232,10.347325,0.0,1003.235956
std,9.551546,10.696847,0.195473,6.913571,107.383428,4.192123,0.0,116.969906
min,-21.822222,-27.716667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.688889,2.311111,0.600000,5.828200,116.000000,8.339800,0.0,1011.900000
50%,12.000000,12.000000,0.780000,9.965900,180.000000,10.046400,0.0,1016.450000
75%,18.838889,18.838889,0.890000,14.135800,290.000000,14.812000,0.0,1021.090000
max,39.905556,39.344444,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000

In [12]:
df.count()

Formatted Date              96453
Summary                     96453
Precip Type                 95936
Temperature (C)             96453
Apparent Temperature (C)    96453
Humidity                    96453
Wind Speed (km/h)           96453
Wind Bearing (degrees)      96453
Visibility (km)             96453
Loud Cover                  96453
Pressure (millibars)        96453
Daily Summary               96453
dtype: int64

In [13]:
df.isnull()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,False,False,False,False,False,False,False,False,False,False,False,False
96449,False,False,False,False,False,False,False,False,False,False,False,False
96450,False,False,False,False,False,False,False,False,False,False,False,False
96451,False,False,False,False,False,False,False,False,False,False,False,False
96452,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [15]:
df.duplicated().sum()

24

In [16]:
df.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [17]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [18]:
df["Apparent Temperature (C)"]

0         7.388889
1         7.227778
2         9.377778
3         5.944444
4         6.977778
           ...
96448    26.016667
96449    24.583333
96450    22.038889
96451    21.522222
96452    20.438889
Name: Apparent Temperature (C), Length: 96453, dtype: float64

In [19]:
df.loc[:, "Apparent Temperature (C)"]

0         7.388889
1         7.227778
2         9.377778
3         5.944444
4         6.977778
           ...
96448    26.016667
96449    24.583333
96450    22.038889
96451    21.522222
96452    20.438889
Name: Apparent Temperature (C), Length: 96453, dtype: float64

In [20]:
df["Apparent Temperature (C)"].value_counts()

 12.777778    378
 17.777778    373
 13.888889    342
 17.222222    330
 12.222222    305
             ...
 35.355556      1
-16.316667      1
-12.038889      1
-12.133333      1
 34.600000      1
Name: Apparent Temperature (C), Length: 8984, dtype: int64

In [21]:
df["Apparent Temperature (C)"].dtype

dtype('float64')

In [22]:
df["Apparent Temperature (C)"].dtypes

dtype('float64')

In [23]:
df.loc[ [10,20] ,["Precip Type", "Loud Cover"] ]

   Precip Type  Loud Cover
10        rain         0.0
20        rain         0.0

In [24]:
x = df.loc[10:20, "Humidity"]

In [25]:
x

10    0.67
11    0.54
12    0.55
13    0.51
14    0.47
15    0.46
16    0.60
17    0.63
18    0.69
19    0.70
20    0.77
Name: Humidity, dtype: float64

In [26]:
for i in x:
    if i == 0.55:
        continue
    else:
        print(i)

0.67
0.54
0.51
0.47
0.46
0.6
0.63
0.69
0.7
0.77

In [27]:
df.loc[[1,3,5,7,9], ["Precip Type", "Humidity"]]

  Precip Type  Humidity
1        rain      0.86
3        rain      0.83
5        rain      0.85
7        rain      0.89
9        rain      0.72

In [28]:
df.loc[10:20, :]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
10,2006-04-01 10:00:00.000 +0200,Partly Cloudy,rain,16.016667,16.016667,0.67,17.5651,290.0,11.2056,0.0,1017.42,Partly cloudy throughout the day.
11,2006-04-01 11:00:00.000 +0200,Partly Cloudy,rain,17.144444,17.144444,0.54,19.7869,316.0,11.4471,0.0,1017.74,Partly cloudy throughout the day.
12,2006-04-01 12:00:00.000 +0200,Partly Cloudy,rain,17.800000,17.800000,0.55,21.9443,281.0,11.2700,0.0,1017.59,Partly cloudy throughout the day.
13,2006-04-01 13:00:00.000 +0200,Partly Cloudy,rain,17.333333,17.333333,0.51,20.6885,289.0,11.2700,0.0,1017.48,Partly cloudy throughout the day.
14,2006-04-01 14:00:00.000 +0200,Partly Cloudy,rain,18.877778,18.877778,0.47,15.3755,262.0,11.4471,0.0,1017.17,Partly cloudy throughout the day.
15,2006-04-01 15:00:00.000 +0200,Partly Cloudy,rain,18.911111,18.911111,0.46,10.4006,288.0,11.2700,0.0,1016.47,Partly cloudy throughout the day.
16,2006-04-01 16:00:00.000 +0200,Partly Cloudy,rain,15.388889,15.388889,0.60,14.4095,251.0,11.2700,0.0,1016.15,Partly cloudy throughout the day.
17,2006-04-01 17:00:00.000 +0200,Mostly Cloudy,rain,15.550000,15.550000,0.63,11.1573,230.0,11.4471,0.0,1016.17,Partly cloudy throughout the day.
18,2006-04-01 18:00:00.000 +0200,Mostly Cloudy,rain,14.255556,14.255556,0.69,8.5169,163.0,11.2056,0.0,1015.82,Partly cloudy throughout the day.
19,2006-04-01 19:00:00.000 +0200,Mostly Cloudy,rain,13.144444,13.144444,0.70,7.6314,139.0,11.2056,0.0,1015.83,Partly cloudy throughout the day.
20,2006-04-01 20:00:00.000 +0200,Mostly Cloudy,rain,11.550000,11.550000,0.77,7.3899,147.0,11.0285,0.0,1015.85,Partly cloudy throughout the day.

In [29]:
df.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [30]:
df.set_index("Formatted Date")

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
Formatted Date,,,,,,,,,,,
2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...
2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [31]:
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [32]:
df.head(1)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.

In [33]:
df.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [34]:
df.index

RangeIndex(start=0, stop=96453, step=1)

In [35]:
df.iloc[0:5, 4]

0    7.388889
1    7.227778
2    9.377778
3    5.944444
4    6.977778
Name: Apparent Temperature (C), dtype: float64

In [36]:
df.loc[0, ["Summary", "Temperature (C)", "Wind Speed (km/h)"]]

Summary              Partly Cloudy
Temperature (C)           9.472222
Wind Speed (km/h)        14.119700
Name: 0, dtype: object

In [37]:
x = df.loc[0:150, ["Temperature (C)","Visibility (km)", "Humidity"]]
x.head(10)
x.isnull().sum()

Temperature (C)    0
Visibility (km)    0
Humidity           0
dtype: int64

In [38]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [39]:
x = df.set_index("Humidity")
x

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
Humidity,,,,,,,,,,,
0.89,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
0.86,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
0.89,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
0.83,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
0.83,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...
0.43,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
0.48,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
0.56,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
0.60,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
0.61,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [40]:
df.sort_index(axis=0)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [41]:
df.sort_index(axis=1)

,Apparent Temperature (C),Daily Summary,Formatted Date,Humidity,Loud Cover,Precip Type,Pressure (millibars),Summary,Temperature (C),Visibility (km),Wind Bearing (degrees),Wind Speed (km/h)
0,7.388889,Partly cloudy throughout the day.,2006-04-01 00:00:00.000 +0200,0.89,0.0,rain,1015.13,Partly Cloudy,9.472222,15.8263,251.0,14.1197
1,7.227778,Partly cloudy throughout the day.,2006-04-01 01:00:00.000 +0200,0.86,0.0,rain,1015.63,Partly Cloudy,9.355556,15.8263,259.0,14.2646
2,9.377778,Partly cloudy throughout the day.,2006-04-01 02:00:00.000 +0200,0.89,0.0,rain,1015.94,Mostly Cloudy,9.377778,14.9569,204.0,3.9284
3,5.944444,Partly cloudy throughout the day.,2006-04-01 03:00:00.000 +0200,0.83,0.0,rain,1016.41,Partly Cloudy,8.288889,15.8263,269.0,14.1036
4,6.977778,Partly cloudy throughout the day.,2006-04-01 04:00:00.000 +0200,0.83,0.0,rain,1016.51,Mostly Cloudy,8.755556,15.8263,259.0,11.0446
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,26.016667,Partly cloudy starting in the morning.,2016-09-09 19:00:00.000 +0200,0.43,0.0,rain,1014.36,Partly Cloudy,26.016667,16.1000,31.0,10.9963
96449,24.583333,Partly cloudy starting in the morning.,2016-09-09 20:00:00.000 +0200,0.48,0.0,rain,1015.16,Partly Cloudy,24.583333,15.5526,20.0,10.0947
96450,22.038889,Partly cloudy starting in the morning.,2016-09-09 21:00:00.000 +0200,0.56,0.0,rain,1015.66,Partly Cloudy,22.038889,16.1000,30.0,8.9838
96451,21.522222,Partly cloudy starting in the morning.,2016-09-09 22:00:00.000 +0200,0.60,0.0,rain,1015.95,Partly Cloudy,21.522222,16.1000,20.0,10.5294
96452,20.438889,Partly cloudy starting in the morning.,2016-09-09 23:00:00.000 +0200,0.61,0.0,rain,1016.16,Partly Cloudy,20.438889,15.5204,39.0,5.8765

In [42]:
df.sort_index( ascending=True, axis=1)

,Apparent Temperature (C),Daily Summary,Formatted Date,Humidity,Loud Cover,Precip Type,Pressure (millibars),Summary,Temperature (C),Visibility (km),Wind Bearing (degrees),Wind Speed (km/h)
0,7.388889,Partly cloudy throughout the day.,2006-04-01 00:00:00.000 +0200,0.89,0.0,rain,1015.13,Partly Cloudy,9.472222,15.8263,251.0,14.1197
1,7.227778,Partly cloudy throughout the day.,2006-04-01 01:00:00.000 +0200,0.86,0.0,rain,1015.63,Partly Cloudy,9.355556,15.8263,259.0,14.2646
2,9.377778,Partly cloudy throughout the day.,2006-04-01 02:00:00.000 +0200,0.89,0.0,rain,1015.94,Mostly Cloudy,9.377778,14.9569,204.0,3.9284
3,5.944444,Partly cloudy throughout the day.,2006-04-01 03:00:00.000 +0200,0.83,0.0,rain,1016.41,Partly Cloudy,8.288889,15.8263,269.0,14.1036
4,6.977778,Partly cloudy throughout the day.,2006-04-01 04:00:00.000 +0200,0.83,0.0,rain,1016.51,Mostly Cloudy,8.755556,15.8263,259.0,11.0446
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,26.016667,Partly cloudy starting in the morning.,2016-09-09 19:00:00.000 +0200,0.43,0.0,rain,1014.36,Partly Cloudy,26.016667,16.1000,31.0,10.9963
96449,24.583333,Partly cloudy starting in the morning.,2016-09-09 20:00:00.000 +0200,0.48,0.0,rain,1015.16,Partly Cloudy,24.583333,15.5526,20.0,10.0947
96450,22.038889,Partly cloudy starting in the morning.,2016-09-09 21:00:00.000 +0200,0.56,0.0,rain,1015.66,Partly Cloudy,22.038889,16.1000,30.0,8.9838
96451,21.522222,Partly cloudy starting in the morning.,2016-09-09 22:00:00.000 +0200,0.60,0.0,rain,1015.95,Partly Cloudy,21.522222,16.1000,20.0,10.5294
96452,20.438889,Partly cloudy starting in the morning.,2016-09-09 23:00:00.000 +0200,0.61,0.0,rain,1016.16,Partly Cloudy,20.438889,15.5204,39.0,5.8765

In [43]:
df.sort_index( ascending=False, axis=1)

,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Temperature (C),Summary,Pressure (millibars),Precip Type,Loud Cover,Humidity,Formatted Date,Daily Summary,Apparent Temperature (C)
0,14.1197,251.0,15.8263,9.472222,Partly Cloudy,1015.13,rain,0.0,0.89,2006-04-01 00:00:00.000 +0200,Partly cloudy throughout the day.,7.388889
1,14.2646,259.0,15.8263,9.355556,Partly Cloudy,1015.63,rain,0.0,0.86,2006-04-01 01:00:00.000 +0200,Partly cloudy throughout the day.,7.227778
2,3.9284,204.0,14.9569,9.377778,Mostly Cloudy,1015.94,rain,0.0,0.89,2006-04-01 02:00:00.000 +0200,Partly cloudy throughout the day.,9.377778
3,14.1036,269.0,15.8263,8.288889,Partly Cloudy,1016.41,rain,0.0,0.83,2006-04-01 03:00:00.000 +0200,Partly cloudy throughout the day.,5.944444
4,11.0446,259.0,15.8263,8.755556,Mostly Cloudy,1016.51,rain,0.0,0.83,2006-04-01 04:00:00.000 +0200,Partly cloudy throughout the day.,6.977778
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,10.9963,31.0,16.1000,26.016667,Partly Cloudy,1014.36,rain,0.0,0.43,2016-09-09 19:00:00.000 +0200,Partly cloudy starting in the morning.,26.016667
96449,10.0947,20.0,15.5526,24.583333,Partly Cloudy,1015.16,rain,0.0,0.48,2016-09-09 20:00:00.000 +0200,Partly cloudy starting in the morning.,24.583333
96450,8.9838,30.0,16.1000,22.038889,Partly Cloudy,1015.66,rain,0.0,0.56,2016-09-09 21:00:00.000 +0200,Partly cloudy starting in the morning.,22.038889
96451,10.5294,20.0,16.1000,21.522222,Partly Cloudy,1015.95,rain,0.0,0.60,2016-09-09 22:00:00.000 +0200,Partly cloudy starting in the morning.,21.522222
96452,5.8765,39.0,15.5204,20.438889,Partly Cloudy,1016.16,rain,0.0,0.61,2016-09-09 23:00:00.000 +0200,Partly cloudy starting in the morning.,20.438889

In [44]:
df.sort_values("Temperature (C)", ascending=False)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
12759,2007-07-22 15:00:00.000 +0200,Clear,rain,39.905556,37.538889,0.13,23.5865,250.0,9.9820,0.0,1007.55,Partly cloudy starting in the afternoon.
12737,2007-07-21 17:00:00.000 +0200,Partly Cloudy,rain,39.588889,37.600000,0.15,12.2038,283.0,10.3523,0.0,1010.24,Partly cloudy starting in the morning continui...
12664,2007-07-19 16:00:00.000 +0200,Partly Cloudy,rain,38.983333,37.461111,0.18,8.9355,175.0,9.9820,0.0,1013.34,Partly cloudy starting in the afternoon.
12712,2007-07-20 16:00:00.000 +0200,Partly Cloudy,rain,38.983333,36.800000,0.15,15.4077,133.0,9.9820,0.0,1011.93,Partly cloudy starting in the afternoon contin...
12711,2007-07-20 15:00:00.000 +0200,Partly Cloudy,rain,38.983333,36.627778,0.14,12.7190,167.0,9.9820,0.0,1012.34,Partly cloudy starting in the afternoon contin...
...,...,...,...,...,...,...,...,...,...,...,...,...
55495,2012-02-09 07:00:00.000 +0100,Foggy,snow,-20.783333,-20.783333,0.80,4.4275,181.0,1.7871,0.0,1032.33,Foggy until morning.
55494,2012-02-09 06:00:00.000 +0100,Foggy,snow,-21.111111,-21.111111,0.71,3.2200,190.0,1.9320,0.0,1032.60,Foggy until morning.
55493,2012-02-09 05:00:00.000 +0100,Foggy,snow,-21.111111,-21.111111,0.78,4.8300,180.0,2.5760,0.0,1033.30,Foggy until morning.
55490,2012-02-09 02:00:00.000 +0100,Foggy,snow,-21.111111,-21.111111,0.74,3.2200,200.0,1.9320,0.0,1034.30,Foggy until morning.
54847,2012-02-10 07:00:00.000 +0100,Foggy,snow,-21.822222,-21.822222,0.80,3.0751,323.0,1.3685,0.0,1033.66,Foggy starting in the morning continuing until...

In [47]:
fltr = df["Daily Summary"].str.contains("Foggy until morning", na=False)

In [51]:
df.loc[fltr, "Daily Summary"]

1968     Foggy until morning.
1969     Foggy until morning.
1970     Foggy until morning.
1971     Foggy until morning.
1972     Foggy until morning.
                 ...
95391    Foggy until morning.
95392    Foggy until morning.
95393    Foggy until morning.
95394    Foggy until morning.
95395    Foggy until morning.
Name: Daily Summary, Length: 2691, dtype: object

In [52]:
df.loc[fltr, "Daily Summary"].count()

2691

In [54]:
df.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [55]:
fltr = (df["Wind Bearing (degrees)"] >250 )

In [59]:
df.loc[fltr]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96426,2016-09-08 21:00:00.000 +0200,Mostly Cloudy,rain,21.016667,21.016667,0.64,3.2200,340.0,16.1000,0.0,1014.73,Partly cloudy starting overnight.
96427,2016-09-08 22:00:00.000 +0200,Partly Cloudy,rain,19.927778,19.927778,0.71,3.1556,302.0,16.1000,0.0,1014.63,Partly cloudy starting overnight.
96430,2016-09-09 01:00:00.000 +0200,Clear,rain,16.622222,16.622222,0.87,3.4293,349.0,16.1000,0.0,1014.56,Partly cloudy starting in the morning.
96433,2016-09-09 04:00:00.000 +0200,Clear,rain,15.011111,15.011111,0.93,3.2039,341.0,15.8263,0.0,1014.37,Partly cloudy starting in the morning.
96434,2016-09-09 05:00:00.000 +0200,Clear,rain,15.016667,15.016667,0.90,2.7048,359.0,14.9569,0.0,1014.55,Partly cloudy starting in the morning.

In [60]:
fltr = (df["Wind Bearing (degrees)"] >250 ) & (df["Wind Bearing (degrees)"] <252 )

In [62]:
df[fltr]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
16,2006-04-01 16:00:00.000 +0200,Partly Cloudy,rain,15.388889,15.388889,0.60,14.4095,251.0,11.2700,0.0,1016.15,Partly cloudy throughout the day.
180,2006-04-16 12:00:00.000 +0200,Overcast,rain,17.844444,17.844444,0.56,22.2180,251.0,11.2700,0.0,1011.28,Mostly cloudy throughout the day.
278,2006-04-02 14:00:00.000 +0200,Partly Cloudy,rain,17.372222,17.372222,0.57,3.6225,251.0,11.4471,0.0,1014.32,Partly cloudy throughout the day.
1104,2006-08-24 00:00:00.000 +0200,Partly Cloudy,rain,13.900000,13.900000,0.92,3.3649,251.0,11.9784,0.0,1016.40,Partly cloudy starting in the morning.
...,...,...,...,...,...,...,...,...,...,...,...,...
94543,2016-11-02 11:00:00.000 +0100,Mostly Cloudy,NaN,8.994444,8.994444,0.76,4.7334,251.0,0.0000,0.0,1020.53,Mostly cloudy until morning.
95537,2016-10-03 21:00:00.000 +0200,Overcast,rain,12.222222,12.222222,0.86,11.1895,251.0,16.1000,0.0,1020.20,Foggy starting overnight continuing until morn...
95599,2016-10-04 10:00:00.000 +0200,Overcast,rain,12.150000,12.150000,0.86,17.2109,251.0,9.7566,0.0,1018.10,Mostly cloudy throughout the day.
95700,2016-10-08 15:00:00.000 +0200,Mostly Cloudy,rain,12.244444,12.244444,0.50,9.2897,251.0,10.2557,0.0,1018.82,Partly cloudy until night.
96351,2016-09-05 18:00:00.000 +0200,Mostly Cloudy,rain,17.294444,17.294444,0.93,9.4185,251.0,9.9820,0.0,1013.04,Mostly cloudy throughout the day.

In [71]:
fltr = df["Precip Type"].str.contains("Rain", na=False)

In [75]:
df.loc[fltr, "Summary"]

Series([], Name: Summary, dtype: object)

In [76]:
fltr = (df["Summary"] == "Mostly Cloudy")

In [80]:
df.loc[fltr, ["Humidity", "Formatted Date"]]

       Humidity                 Formatted Date
2          0.89  2006-04-01 02:00:00.000 +0200
4          0.83  2006-04-01 04:00:00.000 +0200
17         0.63  2006-04-01 17:00:00.000 +0200
18         0.69  2006-04-01 18:00:00.000 +0200
19         0.70  2006-04-01 19:00:00.000 +0200
...         ...                            ...
96412      0.85  2016-09-08 07:00:00.000 +0200
96413      0.78  2016-09-08 08:00:00.000 +0200
96415      0.55  2016-09-08 10:00:00.000 +0200
96416      0.45  2016-09-08 11:00:00.000 +0200
96426      0.64  2016-09-08 21:00:00.000 +0200

[28094 rows x 2 columns]